import os
import json
import logging
from google import genai
from google.genai import types
from google.genai.errors import APIError
from dotenv import load_dotenv
from pydantic import BaseModel

load_dotenv()

API_KEY = os.getenv('GEMINI_API_KEY')
MODEL_NAME = 'gemini-2.5-flash-lite'
SYSTEM_INSTRUCTION = """
You are an expert AI content detection analyst. Your task is to analyze the provided text snippet and determine the probability (0 to 100) that it was primarily generated by a large language model (LLM).

Focus on the following criteria: repetitive phrasing, lack of unique human voice, standardized structure, and unnaturally formal language.

Your response MUST be a JSON object with two keys: "score" (integer 0-100) and "reason" (brief explanation).
"""
class Recipe(BaseModel):
    score: int
    reason: str

def gemini_ai_score(text: str) -> dict:
    if not API_KEY:
        return {'score': -1, 'reason': 'Not found api-key.'}

    try:
        client = genai.Client(api_key=API_KEY)

        config = types.GenerateContentConfig(
            temperature = 0.0,
            response_mime_type='application/json',
            response_schema= Recipe,
            system_instruction=SYSTEM_INSTRUCTION
        )
        prompt = f"""
        Analyze the following text and provide the AI generation probability score based on the criteria provided:
        --- TEXT BEGIN ---
        {text[:8000]}
        --- TEXT END ---
        """

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=prompt,
            config=config
        )

        res_text = response.text.strip() if response.text is not None else ""
        result = json.loads(res_text)

        score = max(0, min(100, int(result.get('score', 0))))
        reason = result.get('reason', 'Analysis not available.')

        return {'score': score, 'reason': reason}

    except APIError as e:
        msg = str(e)
        logging.error(f"Gemini API Error: {e}")
        if 'UNAUTHENTICATED' in msg or 'API keys are not supported' in msg or 'CREDENTIALS' in msg:
            logging.warning("Authentication issue detected from Gemini API — falling back to local heuristic.")
            return {"score": -1, "reason": "UNAUTHENTICATED API key issue."}
        return {"score": -1, "reason": f"API Call Error: {str(e)}"}
    except json.JSONDecodeError:
        logging.error(f"Gemini returned unparseable JSON: {response.text}")
        return {"score": -1, "reason": "AI output format error."}
    except Exception as e:
        logging.error(f"An unexpected error occurred: {e}")
        return {"score": -1, "reason": f"Unexpected error: {str(e)}"}
